/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabRouteImport } from './routes/lab'
import { Route as AlgorithmsIndexRouteImport } from './routes/algorithms/index'
import { Route as AlgorithmsSlugRouteImport } from './routes/algorithms/$slug'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as StrategiesSlugRouteImport } from './routes/strategies/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsIndexRoute = AlgorithmsIndexRouteImport.update({
  id: '/algorithms/',
  path: '/algorithms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsSlugRoute = AlgorithmsSlugRouteImport.update({
  id: '/algorithms/$slug',
  path: '/algorithms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesSlugRoute = StrategiesSlugRouteImport.update({
  id: '/strategies/$slug',
  path: '/strategies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/algorithms': typeof AlgorithmsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lab': typeof LabRoute
  '/algorithms/$slug': typeof AlgorithmsSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/algorithms/': typeof AlgorithmsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/algorithms/$slug'
    | '/strategies/$slug'
    | '/algorithms/'
    | '/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab'
    | '/algorithms/$slug'
    | '/strategies/$slug'
    | '/algorithms'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/lab'
    | '/algorithms/$slug'
    | '/strategies/$slug'
    | '/algorithms/'
    | '/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabRoute: typeof LabRoute
  AlgorithmsSlugRoute: typeof AlgorithmsSlugRoute
  StrategiesSlugRoute: typeof StrategiesSlugRoute
  AlgorithmsIndexRoute: typeof AlgorithmsIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/': {
      id: '/algorithms/'
      path: '/algorithms'
      fullPath: '/algorithms/'
      preLoaderRoute: typeof AlgorithmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/$slug': {
      id: '/algorithms/$slug'
      path: '/algorithms/$slug'
      fullPath: '/algorithms/$slug'
      preLoaderRoute: typeof AlgorithmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$slug': {
      id: '/strategies/$slug'
      path: '/strategies/$slug'
      fullPath: '/strategies/$slug'
      preLoaderRoute: typeof StrategiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabRoute: LabRoute,
  AlgorithmsSlugRoute: AlgorithmsSlugRoute,
  StrategiesSlugRoute: StrategiesSlugRoute,
  AlgorithmsIndexRoute: AlgorithmsIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
